// server.js
// Facebook Page automation backend — Messenger auto-reply + comment auto-reply,
// replies generated by Claude (Anthropic API).

require('dotenv').config();
const express = require('express');
const crypto = require('crypto');
const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');

const app = express();

// Keep the raw body around so we can verify Facebook's X-Hub-Signature-256 header.
app.use(express.json({
  verify: (req, res, buf) => { req.rawBody = buf; }
}));

const {
  VERIFY_TOKEN,        // you choose this string yourself, must match what you enter in the Meta dashboard
  PAGE_ACCESS_TOKEN,   // from your Meta app > Messenger > page token
  APP_SECRET,          // from your Meta app > Settings > Basic
  ANTHROPIC_API_KEY,   // from console.anthropic.com
  GRAPH_API_VERSION = 'v19.0',
  PORT = 3000
} = process.env;

const REQUIRED = { VERIFY_TOKEN, PAGE_ACCESS_TOKEN, APP_SECRET, ANTHROPIC_API_KEY };
for (const [key, val] of Object.entries(REQUIRED)) {
  if (!val) console.warn(`⚠️  Missing env var: ${key} — set it before going live.`);
}

function loadProfile() {
  const raw = fs.readFileSync(path.join(__dirname, 'business-profile.json'), 'utf8');
  return JSON.parse(raw);
}

// ---------- Claude reply generation ----------

async function generateReply({ kind, userText }) {
  const profile = loadProfile();
  const ctx = `ব্যবসার নাম: ${profile.name}
ধরন: ${profile.category}
কথার স্টাইল: ${profile.tone}
প্রোডাক্ট/সার্ভিস তথ্য: ${profile.info}`;

  const roleLine = {
    comment: 'তুমি একজন ফেসবুক পেজ কাস্টমার সাপোর্ট এজেন্ট। নিচের ব্যবসার তথ্যের ভিত্তিতে কাস্টমারের কমেন্টের একটি সংক্ষিপ্ত, বন্ধুত্বপূর্ণ ও সহায়ক রিপ্লাই বাংলায় লেখো। শুধু রিপ্লাইটাই লিখবে, অতিরিক্ত কিছু না।',
    message: 'তুমি একজন ফেসবুক মেসেঞ্জার কাস্টমার সাপোর্ট এজেন্ট। নিচের ব্যবসার তথ্যের ভিত্তিতে কাস্টমারের মেসেজের একটি স্বাভাবিক, আন্তরিক উত্তর বাংলায় লেখো, যেন সত্যিকারের দোকানদার নিজে উত্তর দিচ্ছে। শুধু উত্তরটাই লিখবে।'
  }[kind];

  const prompt = `${roleLine}\n\n${ctx}\n\nকাস্টমারের বার্তা: "${userText}"`;

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 400,
      messages: [{ role: 'user', content: prompt }]
    })
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Anthropic API error ${res.status}: ${errText}`);
  }
  const data = await res.json();
  const textBlock = (data.content || []).find(b => b.type === 'text');
  return textBlock ? textBlock.text.trim() : null;
}

function needsHumanHandoff(text) {
  const profile = loadProfile();
  const keywords = profile.human_handoff_keywords || [];
  return keywords.some(k => text.includes(k));
}

// ---------- Facebook send helpers ----------

async function sendMessengerReply(recipientId, text) {
  const url = `https://graph.facebook.com/${GRAPH_API_VERSION}/me/messages?access_token=${PAGE_ACCESS_TOKEN}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      recipient: { id: recipientId },
      message: { text }
    })
  });
  if (!res.ok) console.error('Messenger send failed:', await res.text());
}

async function replyToComment(commentId, text) {
  const url = `https://graph.facebook.com/${GRAPH_API_VERSION}/${commentId}/comments?access_token=${PAGE_ACCESS_TOKEN}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message: text })
  });
  if (!res.ok) console.error('Comment reply failed:', await res.text());
}

// ---------- Webhook verification (GET) ----------
// Meta calls this once, when you save the webhook URL in the App Dashboard.

app.get('/webhook', (req, res) => {
  const mode = req.query['hub.mode'];
  const token = req.query['hub.verify_token'];
  const challenge = req.query['hub.challenge'];

  if (mode === 'subscribe' && token === VERIFY_TOKEN) {
    console.log('✅ Webhook verified');
    return res.status(200).send(challenge);
  }
  return res.sendStatus(403);
});

// ---------- Signature check ----------

function isValidSignature(req) {
  const signature = req.headers['x-hub-signature-256'];
  if (!signature || !req.rawBody) return false;
  const expected = 'sha256=' + crypto
    .createHmac('sha256', APP_SECRET)
    .update(req.rawBody)
    .digest('hex');
  try {
    return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected));
  } catch {
    return false;
  }
}

// ---------- Incoming events (POST) ----------

app.post('/webhook', async (req, res) => {
  // Acknowledge immediately — Facebook expects a fast 200, do the work after.
  res.status(200).send('EVENT_RECEIVED');

  if (!isValidSignature(req)) {
    console.warn('⚠️  Invalid signature, ignoring event');
    return;
  }

  const body = req.body;
  if (body.object !== 'page') return;

  for (const entry of body.entry || []) {
    // --- Messenger messages ---
    for (const event of entry.messaging || []) {
      try {
        const senderId = event.sender && event.sender.id;
        const text = event.message && event.message.text;
        if (!senderId || !text) continue;
        if (event.message.is_echo) continue; // ignore our own sent messages

        if (needsHumanHandoff(text)) {
          console.log(`🙋 Human handoff needed for ${senderId}: "${text}"`);
          continue; // let a real person take over — no auto reply sent
        }

        const profile = loadProfile();
        if (!profile.auto_reply_messages) continue;

        const reply = await generateReply({ kind: 'message', userText: text });
        if (reply) await sendMessengerReply(senderId, reply);
      } catch (err) {
        console.error('Error handling message event:', err);
      }
    }

    // --- Page feed comments ---
    for (const change of entry.changes || []) {
      try {
        if (change.field !== 'feed') continue;
        const value = change.value || {};
        if (value.item !== 'comment' || value.verb !== 'add') continue;

        const commentId = value.comment_id;
        const text = value.message;
        if (!commentId || !text) continue;

        // Don't reply to the page's own comments
        if (value.from && value.from.id === entry.id) continue;

        if (needsHumanHandoff(text)) {
          console.log(`🙋 Human handoff needed for comment ${commentId}: "${text}"`);
          continue;
        }

        const profile = loadProfile();
        if (!profile.auto_reply_comments) continue;

        const reply = await generateReply({ kind: 'comment', userText: text });
        if (reply) await replyToComment(commentId, reply);
      } catch (err) {
        console.error('Error handling comment event:', err);
      }
    }
  }
});

// ---------- Health check ----------

app.get('/', (req, res) => {
  res.send('FB AI automation backend is running ✅');
});

app.listen(PORT, () => {
  console.log(`🚀 Server listening on port ${PORT}`);
});
